[project]
name = "daily-ai-digest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arslan Tariq", email = "arslantariq25@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.3",
]

[project.scripts]
daily-ai-digest = "daily_ai_digest:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
